[theme]
primaryColor = "#39FF14" # Neon green
backgroundColor = "#121212" # Dark mode background
secondaryBackgroundColor = "#1E1E1E" # Dark grey background
textColor = "#FFFFFF" # White for better contrast
font = "monospace"
